# Generated by Django 5.2.7 on 2025-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('love', 'Романтика'), ('horror', 'Ужасы'), ('fantasy', 'Фантастика'), ('life', 'Из жизни'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
